CREATE TABLE user_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_email UNIQUE (email),
    CONSTRAINT ck_user_role CHECK (role IN ('STUDENT', 'INSTRUCTOR', 'TEACHING_ASSISTANT'))
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(160) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_courses_published_created ON courses(published, created_at DESC);

CREATE TABLE course_instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    instructor_id BIGINT NOT NULL REFERENCES user_accounts(id),
    CONSTRAINT uk_course_instructor UNIQUE (course_id, instructor_id)
);

CREATE TABLE course_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    ta_id BIGINT NOT NULL REFERENCES user_accounts(id),
    title VARCHAR(160) NOT NULL,
    sheet_url VARCHAR(1000) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT uk_section_position UNIQUE (course_id, position),
    CONSTRAINT ck_section_position CHECK (position > 0)
);

CREATE TABLE lectures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    instructor_id BIGINT NOT NULL REFERENCES user_accounts(id),
    title VARCHAR(160) NOT NULL,
    presentation_url VARCHAR(1000) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT uk_lecture_position UNIQUE (course_id, position),
    CONSTRAINT ck_lecture_position CHECK (position > 0)
);
CREATE TABLE assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL REFERENCES course_sections(id) ON DELETE CASCADE,
    title VARCHAR(160) NOT NULL,
    instructions VARCHAR(4000) NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_assignment_section UNIQUE (section_id)
);

CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES user_accounts(id),
    course_id BIGINT NOT NULL REFERENCES courses(id),
    status VARCHAR(20) NOT NULL,
    enrolled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_enrollment_student_course UNIQUE (student_id, course_id),
    CONSTRAINT ck_enrollment_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);
CREATE INDEX ix_enrollments_student_date ON enrollments(student_id, enrolled_at DESC);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assignment_id BIGINT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES user_accounts(id),
    submission_url VARCHAR(1000) NOT NULL,
    submitted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    grade INTEGER,
    feedback VARCHAR(4000),
    CONSTRAINT uk_submission_assignment_student UNIQUE (assignment_id, student_id),
    CONSTRAINT ck_submission_grade CHECK (grade IS NULL OR grade BETWEEN 0 AND 100)
);
